config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    resources :users, only: [:show, :new, :create]
    resources :asks, only: [:index, :show, :new, :create, :destroy]
    resources :ningens, only: [:index]
    resources :jukens, only: [:index]
    resources :renais, only: [:index]
    resources :kenkous, only: [:index]
    resources :sonotas, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ask.rb
class Ask < ApplicationRecord
  belongs_to :user
  # belongs_to :category
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, length: {maximum: 50}
    
    # has_many :asks
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email.downcase! }
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255}, 
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :asks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
end

app/controllers/asks_controller.rb
class AsksController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :new]
  
  def index
    @asks = Ask.all.order(id: :desc).page(params[:page])
  end

  def show
    @ask = Ask.find(params[:id])
  end

  def new
    @ask = current_user.asks.new
  end

  def create
    @ask = Ask.new(ask_params)
    
    if @ask.save
      flash[:success] = 'お悩みを投稿しました'
      redirect_to asks_path
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def destroy
    @ask = Ask.find(params[:id])
    @ask.destroy
    flash[:success] = 'お悩みを削除しました'
    redirect_back(fallback_location: asks_path)
  end
  
  private
  
  def ask_params
    params.require(:ask).permit(:title, :content, :user_id)
  end
  
  def correct_user
    @ask = current_user.asks.find_by(id: params[:id])
    unless @ask
    redirect_to root_url
    end
  end
end

app/controllers/catigories_controller.rb
class CatigoriesController < ApplicationController
  def new
  end

  # def create
  #   @category = Category.find(params[:id])
  #   if @category.save
  #     redirect_to asks_path
  #   else
  #     render new_ask_path
  #   end
  # end

  def destroy
  end
end

app/controllers/jukens_controller.rb
class JukensController < ApplicationController
  def index
    @asks = Ask.where(category_id: 2)
    @category = Category.find(2)
  end
end

app/controllers/kenkous_controller.rb
class KenkousController < ApplicationController
  def index
    @asks = Ask.where(category_id: 4)
    @category = Category.find(4)
  end
end

app/controllers/ningens_controller.rb
class NingensController < ApplicationController
  def index
    @asks = Ask.where(category_id: 1)
    @category = Category.find(1)
  end
end

app/controllers/renais_controller.rb
class RenaisController < ApplicationController
  def index
    @asks = Ask.where(category_id: 3)
    @category = Category.find(3)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render layout: false
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      flash[:success] = 'ログインに成功しました'
      redirect_to asks_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'sessions/new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
end

app/controllers/sonotas_controller.rb
class SonotasController < ApplicationController
  def index
    @asks = Ask.where(category_id: 5)
    @category = Category.find(5)
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    render layout: false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    render layout: false
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to root_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
end

app/views/asks/index.html.erb
        <div class="text-center mt-5 mb-5">
            <h3>お悩み一覧</h3>
        </div>
        
        <% @asks.each do |ask| %>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title mb-2"><%= ask.title %></h5>
                    <p class="card-text"><%= ask.content %></p>
                    <!--<p class="card-text">カテゴリー：</p>-->
                    <%= link_to '詳しく見る', ask_path(ask) %>
                </div>
            </div>
        <% end %>

app/views/asks/new.html.erb
<div class="text-center pt-5 mb-5">
    <h3>悩みを投稿する</h3>
</div>


        <%= form_with(model: @ask, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
            <div class="form-group">
                <%= f.label :title, 'Title' %>
                <%= f.text_field :title, class: 'form-control' %>
            </div>
            
            <div class="form-group">
                <%= f.label :content, 'Content' %>
                <%= f.text_field :content, class: 'form-control', style: 'height: 100px;', cols: '20', wrap: 'hard' %>
            </div>
            
            <!--<div class="form-group">-->
            <!--    <%= f.label :category_name, 'Category' %>-->
            <!--    <%= f.select :name, [["人間関係", 1], ["受験", 2], ["恋愛", 3], ["健康", 4], ["その他", 5]] %>-->
                
            <!--</div>-->
            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="text-center">
                <%= f.submit '投稿する', class: 'btn btn-primary  mt-5' %>
            </div>
        <% end %>
  

app/views/asks/show.html.erb
<div class="text-center pt-5 mb-5">
    <h5><%= @ask.user.name %>さんのお悩み</h5>
</div>

        <div class="card" style="min-height: 330px; max-height: 100%;">
            <div class="card-head">
                <h4 class="card-title pt-3 pl-3 mb-2"><%= @ask.title %></h4>
            </div>
            <div class="card-body">
                <h5 class="card-text"><%= @ask.content %></h5>
                <!--<p class="card-text">カテゴリー：</p>-->
            </div>
        </div>
        <div class="text-center mt-3">
            <%= link_to '一覧に戻る', asks_path %>
        </div>

app/views/catigories/new.html.erb
<h1>Catigories#new</h1>
<p>Find me in app/views/catigories/new.html.erb</p>

app/views/jukens/index.html.erb
<%= render 'shares/share', asks: @asks, category: @category %>

app/views/kenkous/index.html.erb
<%= render 'shares/share', asks: @asks, category: @category %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
        <%= message %>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<style type="text/css">
      header {
          background-color: #FAEBD7;
      }  
</style>

<header>
    <div class="pt-5 pr-5 pb-5" style="margin-top: 129px;">
    <div class="list-group">
        <label class="list-group-item text-center", style="background-color: #5bc0de; color: #fff;">メニュー</label>
            <%= link_to 'お悩み一覧', asks_path, class: 'list-group-item', style: 'text-decoration: none; text-align: center;' %>
            <%= link_to '投稿する', new_ask_path, class: 'list-group-item', style: 'text-decoration: none; text-align: center;' %>
            <%= link_to 'マイページ', user_path(current_user.id), class: 'list-group-item', style: 'text-decoration: none; text-align: center;' %>
            <%= link_to 'Logout', logout_path, method: :delete, class: 'list-group-item', style: 'text-decoration: none; text-align: center;' %>
    </div>
       
            
                
                
                    <!--<a href="#" class="dropdown-toggle btn btn-default btn-outline-info w-100", style="height: 35px;", data-toggle="dropdown" role="button">カテゴリー別にみる<span class="caret"></span></a>-->
                    <!--<div class="dropdown-menu" role="menu">-->
                    <!--        <%= link_to '人間関係', ningens_path, class: 'dropdown-item btn-info' %>-->
                    <!--        <%= link_to '受験', jukens_path, class: 'dropdown-item btn-info' %>-->
                    <!--        <%= link_to '恋愛', renais_path, class: 'dropdown-item btn-info' %>-->
                    <!--        <%= link_to '健康', kenkous_path, class: 'dropdown-item btn-info' %>-->
                    <!--        <%= link_to 'その他', sonotas_path, class: 'dropdown-item btn-info' %>-->
                    <!--</div>-->
                    
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Asks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <style type="text/css">
      
      .container-fluid {
        min-height: 800px;
        height: 100%;
        background-color: #FAEBD7;
        
      }
    </style>
    
    <link rel='stylesheet' href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    
    
    <div class="container-fluid">
      <div class="text-center pt-5 pb-2 mb-2" style="background-color: #5bc0de; ">
        <%= link_to 'Asks', asks_path, style: "color: #fff; font-size: 30px; text-decoration: none;" %>
      </div>
      <div class="row">
        <div class="col-sm-3 offset-sm-1">
           <%= render 'layouts/navbar' %>
        </div>
        <div class="col-sm-7">
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </div>
    
  </body>
</html>

app/views/ningens/index.html.erb
<%= render 'shares/share', asks: @asks, category: @category %>

app/views/shares/_share.html.erb
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <div class="text-center mt-5 mb-5">
            <h3>カテゴリー：<%= category.name %>の投稿</h3>
        </div>
        
        <% asks.each do |ask| %>
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title mb-2"><%= ask.title %></h5>
                    <p class="card-text"><%= ask.content %></p>
                    <p class="card-text">カテゴリー：<%= ask.category.name %></p>
                    <%= link_to '詳しく見る', ask_path(ask) %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/sonotas/index.html.erb
<%= render 'shares/share', asks: @asks, category: @category %>

app/views/toppages/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Asks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style type="text/css">
        .all {
            background-color: #FAEBD7;
            min-height: 700px;
            max-height: 100%;
        }
    </style>
    <link rel='stylesheet' href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="all">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
                <%= message %>
            </div>
        <% end %>

        <style>
            .jumbotron{
                background:url(https://girlydrop.com/wp-content/uploads/2017/03/IMG_2262_s.jpeg)center no-repeat;
                background-size:cover;
                width: 100%;
                height: 600px;
            }
        </style>
        <div class="jumbotron jumbotron-fluid">
            <div class="container-fluid">
                <div class="text-center" style="color: #555555;">
                    <h1>Asks</h1>
                </div>
            </div>
        </div>
    
    
    <div class="text-center mt-5">
        <h4>ここはあなたの悩みについて投稿できる場所です</h4>
    </div>
    
    <div class="text-center mt-5 mb-5">
        <p>相談するにはユーザ登録が必要です</p>
        <p>下のボタンからユーザ登録をお願いします</p>
        <%= link_to 'Sign up', signup_path, class: "btn btn-primary" %>
    </div>
    
    <div class="text-center mt-5 ">
        <p>登録済みの方はこちら</p>
        <%= link_to 'Log in', login_path, class: 'btn btn-primary mb-5' %>
    </div>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Asks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style type="text/css">
        .container-fluid {
            background-color: #FAEBD7;
            min-height: 700px;
            max-height: 100%;
        }
    </style>
    <link rel='stylesheet' href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <div class="text-center pt-5 pb-2 pb-2" style="background-color: #5bc0de; ">
        <%= link_to 'Asks', root_path, style: "color: #fff; font-size: 30px; text-decoration: none;" %>
    </div>
    <div class="container-fluid">
      <%= render 'layouts/flash_messages' %>
      <div class="text-center pt-5 mb-5">
          <h2>Sign up</h2>
      </div>
      
      <div class="row">
          <div class="col-sm-6 offset-sm-3">
              <%= form_with(model: @user, local: true) do |f| %>
              <%= render 'layouts/error_messages', model: f.object %>
                  <div class="form-group">
                      <%= f.label :name, 'Name' %>
                      <%= f.text_field :name, class: 'form-control' %>
                  </div>
                  
                  <div class="form-group">
                      <%= f.label :email, 'Email' %>
                      <%= f.email_field :email, class: 'form-control' %>
                  </div>
                  
                  <div class="form-group">
                      <%= f.label :password, 'Password' %>
                      <%= f.password_field :password, class: 'form-control' %>
                  </div>
                  
                  <div class="form-group">
                      <%= f.label :password_confirmation, 'Confirmation' %>
                      <%= f.password_field :password_confirmation, class: 'form-control' %>
                  </div>
                  <div class="text-center">
                    <%= f.submit 'Sign up', class: 'btn btn-primary' %>
                  </div>
            <% end %>
            <div class="text-center mt-5 mb-5">
                <p>登録済みの方はこちら</p>
                <%= link_to 'Log in', login_path, class: 'btn btn-primary' %>
            </div>
          </div>
      </div>
    </div>
    
  </body>
</html>

app/views/users/show.html.erb
<div class="text-center pt-2 pb-1">
    <p>ようこそ、<%= @user.name %>さん</p>
</div>
<div class="text-center mb-5">
    <h3><%= @user.name %>さんのこれまでの投稿</h3>
</div>
<% @user.asks.each do |ask| %>
    
            <div class="card mb-3">
                <div class="card-body">
                     <h5 class="card-title mb-2"><%= ask.title %></h5> 
                    <p class="card-text"><%= ask.content %></p>
                    <!--<p class="card-text">カテゴリー：</p>-->
                    <%= link_to "削除", ask, method: :delete, data: {confirm: "You sure?"}, class: 'btn btn-danger' %>
                </div>
            </div>
     
<% end %>